---
upload_path: "/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: 'https://app.forestry.io/sites/ckfgevllcw05bq/media//uploads/2018/02/02/wat-hou-ik-eraan-over.jpg//uploads/:year:/:month:/:day:'
new_page_extension: html
auto_deploy: false
admin_path: 
webhook_url: ''
collections: 
